# --- Created by Ebean DDL
# To stop Ebean DDL generation, remove this comment and start using Evolutions

# --- !Ups

-- apply changes
create table recipe_avatar (
  id                            bigint generated by default as identity not null,
  url                           varchar(255),
  constraint pk_recipe_avatar primary key (id)
);

create table recipe_model (
  id                            bigint generated by default as identity not null,
  name                          varchar(255),
  age                           integer,
  avatar_id                     bigint,
  constraint uq_recipe_model_avatar_id unique (avatar_id),
  constraint pk_recipe_model primary key (id)
);

create table recipe_password (
  id                            bigint generated by default as identity not null,
  parent_recipe_id              bigint,
  password_hash                 varchar(255),
  constraint pk_recipe_password primary key (id)
);

-- foreign keys and indices
alter table recipe_model add constraint fk_recipe_model_avatar_id foreign key (avatar_id) references recipe_avatar (id) on delete restrict on update restrict;

create index ix_recipe_password_parent_recipe_id on recipe_password (parent_recipe_id);
alter table recipe_password add constraint fk_recipe_password_parent_recipe_id foreign key (parent_recipe_id) references recipe_model (id) on delete restrict on update restrict;


# --- !Downs

-- drop all foreign keys
alter table recipe_model drop constraint if exists fk_recipe_model_avatar_id;

alter table recipe_password drop constraint if exists fk_recipe_password_parent_recipe_id;
drop index if exists ix_recipe_password_parent_recipe_id;

-- drop all
drop table if exists recipe_avatar;

drop table if exists recipe_model;

drop table if exists recipe_password;

