# --- Created by Ebean DDL
# To stop Ebean DDL generation, remove this comment and start using Evolutions

# --- !Ups

-- apply changes
create table recipe_ingredient (
  id                            bigint generated by default as identity not null,
  nombre_ingrediente            varchar(255),
  constraint pk_recipe_ingredient primary key (id)
);

create table recipe_model (
  id                            bigint generated by default as identity not null,
  name                          varchar(255),
  time                          integer,
  type_food                     varchar(255),
  title_id                      bigint,
  constraint uq_recipe_model_title_id unique (title_id),
  constraint pk_recipe_model primary key (id)
);

create table recipe_model_recipe_ingredient (
  recipe_model_id               bigint not null,
  recipe_ingredient_id          bigint not null,
  constraint pk_recipe_model_recipe_ingredient primary key (recipe_model_id,recipe_ingredient_id)
);

create table recipe_title (
  id                            bigint generated by default as identity not null,
  title                         varchar(255),
  constraint pk_recipe_title primary key (id)
);

create table recipe_valoration (
  id                            bigint generated by default as identity not null,
  parent_recipe_id              bigint,
  puntuation                    integer,
  constraint pk_recipe_valoration primary key (id)
);

-- foreign keys and indices
alter table recipe_model add constraint fk_recipe_model_title_id foreign key (title_id) references recipe_title (id) on delete restrict on update restrict;

create index ix_recipe_model_recipe_ingredient_recipe_model on recipe_model_recipe_ingredient (recipe_model_id);
alter table recipe_model_recipe_ingredient add constraint fk_recipe_model_recipe_ingredient_recipe_model foreign key (recipe_model_id) references recipe_model (id) on delete restrict on update restrict;

create index ix_recipe_model_recipe_ingredient_recipe_ingredient on recipe_model_recipe_ingredient (recipe_ingredient_id);
alter table recipe_model_recipe_ingredient add constraint fk_recipe_model_recipe_ingredient_recipe_ingredient foreign key (recipe_ingredient_id) references recipe_ingredient (id) on delete restrict on update restrict;

create index ix_recipe_valoration_parent_recipe_id on recipe_valoration (parent_recipe_id);
alter table recipe_valoration add constraint fk_recipe_valoration_parent_recipe_id foreign key (parent_recipe_id) references recipe_model (id) on delete restrict on update restrict;


# --- !Downs

-- drop all foreign keys
alter table recipe_model drop constraint if exists fk_recipe_model_title_id;

alter table recipe_model_recipe_ingredient drop constraint if exists fk_recipe_model_recipe_ingredient_recipe_model;
drop index if exists ix_recipe_model_recipe_ingredient_recipe_model;

alter table recipe_model_recipe_ingredient drop constraint if exists fk_recipe_model_recipe_ingredient_recipe_ingredient;
drop index if exists ix_recipe_model_recipe_ingredient_recipe_ingredient;

alter table recipe_valoration drop constraint if exists fk_recipe_valoration_parent_recipe_id;
drop index if exists ix_recipe_valoration_parent_recipe_id;

-- drop all
drop table if exists recipe_ingredient;

drop table if exists recipe_model;

drop table if exists recipe_model_recipe_ingredient;

drop table if exists recipe_title;

drop table if exists recipe_valoration;

